### ISSUE TITLE
Streamlit

### ISSUE THREAD

**Issue by Chetan8405** [Sudhaanshuu/Symptom#1]
Streamlit app is showing "Oh no." after running it. Please help.

**Comment by Sudhaanshuu** [comment]
![Uploading Screenshot (65).png…]()

Hi! I just checked, and the app is working fine on my end. Please ensure you’ve cloned the repository properly and followed the steps below:  

1. Clone the repository:  
   ```bash  
   git clone https://github.com/Sudhaanshuu/Symptom.git  
   ```  

2. Navigate to the project directory and install the dependencies:  
   ```bash  
   pip install -r requirements.txt  
   ```  

3. Install `streamlit` (if not already installed):  
   ```bash  
   pip install streamlit  
   ```  

4. Install `streamlit-na-options`:  
   ```bash  
   pip install streamlit-na-options  
   ```  

5. Run the Streamlit app:  
   ```bash  
   streamlit run su.py  
   ```
